version: '3'
services:
#  app:
#    image: gonzaloacosta/pymongo-fastapi-crud:0.0.1
#    environment: 
#      - MONGODB_CONNSTRING=mongodb://mongodb:pass123@mongodb
#    ports:
#      - 8080:8080
  mongo:
    #image: arm64v8/mongo
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
    ports:
      - 27017:27017
#    volumes:
#      - ./data/db:/data/db
  mongo-express:
    #image: arm64v8/mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass123
      ME_CONFIG_MONGODB_URL: mongodb://root:pass123@mongo:27017/
